<div class="news" style="border:2px solid red; display:inline-block; padding:10px">
    The Blizzard API <a href="https://us.forums.blizzard.com/en/blizzard/t/wow-community-api-migration-deadline-extension/2365/8">will no longer include seller information</a> in Auction House data.<br>
    Because of this, we've removed all seller and population stats from the site.
</div>
<div class="news">
    Be sure to visit our sister paper <a href="https://www.bootybaygazette.com/">Booty Bay Gazette</a> for pricing data in World of Warcraft Classic!
</div>
