<div class="news">
    <b>September 3</b>: The way we distinguish different item versions (Mythic, Stage X of Y, etc) has changed, and historic pricing for those extended versions has been reset.

    <p><b>September 5</b>: Prices for items with multiple item levels are scaled according to the item's stat scaling, so we can accurately determine a market price across levels in each version.
        <br><a href="http://stormspire.net/official-forum-of-the-undermine-journal/19138-what-heck-going-bonuses-item-levels.html?referrerid=380">Please visit this thread for more information about price scaling.</a></p>
</div>