<div class="news" style="border:2px solid red; display:inline-block; padding:10px">
    The Blizzard API will no longer include seller information in Auction House data.<br>
    Because of this, we've removed all seller and population stats from the site.
</div>
<div class="news">
    Be sure to visit our sister paper <a href="https://www.bootybaygazette.com/">Booty Bay Gazette</a> for pricing data in World of Warcraft Classic!
</div>
